// ARCHIVO GENERADO — no lo edites a mano.
// Se regenera con: npm run catalogo:generar
// Los precios y los textos del catálogo están en content/catalogo.ts.

export type PiezaGenerada = {
  /** Referencia que ve el cliente y que usa para pedir por WhatsApp. */
  ref: string;
  src: string;
  ancho: number;
  alto: number;
};

export const PIEZAS: Record<string, PiezaGenerada[]> = {
  'cirios-basicos': [
    { ref: 'CP-B-01', src: '/images/colecciones/cirios-basicos/cirios-basicos-01.webp', ancho: 1200, alto: 1600 },
    { ref: 'CP-B-02', src: '/images/colecciones/cirios-basicos/cirios-basicos-02.webp', ancho: 1200, alto: 1200 },
    { ref: 'CP-B-03', src: '/images/colecciones/cirios-basicos/cirios-basicos-03.webp', ancho: 1200, alto: 1500 },
    { ref: 'CP-B-04', src: '/images/colecciones/cirios-basicos/cirios-basicos-04.webp', ancho: 1200, alto: 1500 },
    { ref: 'CP-B-05', src: '/images/colecciones/cirios-basicos/cirios-basicos-05.webp', ancho: 1200, alto: 1600 },
    { ref: 'CP-B-06', src: '/images/colecciones/cirios-basicos/cirios-basicos-06.webp', ancho: 1600, alto: 1600 },
    { ref: 'CP-B-07', src: '/images/colecciones/cirios-basicos/cirios-basicos-07.webp', ancho: 1200, alto: 1600 },
    { ref: 'CP-B-08', src: '/images/colecciones/cirios-basicos/cirios-basicos-08.webp', ancho: 1200, alto: 1600 },
    { ref: 'CP-B-09', src: '/images/colecciones/cirios-basicos/cirios-basicos-09.webp', ancho: 1600, alto: 1600 },
    { ref: 'CP-B-10', src: '/images/colecciones/cirios-basicos/cirios-basicos-10.webp', ancho: 1200, alto: 1600 },
  ],
  'cirios-elaborados': [
    { ref: 'CP-E-01', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-01.webp', ancho: 1200, alto: 1496 },
    { ref: 'CP-E-02', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-02.webp', ancho: 1200, alto: 900 },
    { ref: 'CP-E-03', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-03.webp', ancho: 1200, alto: 1200 },
    { ref: 'CP-E-04', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-04.webp', ancho: 1200, alto: 1600 },
    { ref: 'CP-E-05', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-05.webp', ancho: 1200, alto: 1600 },
    { ref: 'CP-E-06', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-06.webp', ancho: 300, alto: 300 },
    { ref: 'CP-E-07', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-07.webp', ancho: 1600, alto: 1600 },
    { ref: 'CP-E-08', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-08.webp', ancho: 224, alto: 300 },
    { ref: 'CP-E-09', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-09.webp', ancho: 224, alto: 300 },
    { ref: 'CP-E-10', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-10.webp', ancho: 1280, alto: 1600 },
    { ref: 'CP-E-11', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-11.webp', ancho: 224, alto: 300 },
    { ref: 'CP-E-12', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-12.webp', ancho: 1600, alto: 1200 },
    { ref: 'CP-E-13', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-13.webp', ancho: 1200, alto: 1600 },
    { ref: 'CP-E-14', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-14.webp', ancho: 1200, alto: 1600 },
    { ref: 'CP-E-15', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-15.webp', ancho: 1600, alto: 1600 },
    { ref: 'CP-E-16', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-16.webp', ancho: 1200, alto: 1600 },
    { ref: 'CP-E-17', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-17.webp', ancho: 1600, alto: 1200 },
    { ref: 'CP-E-18', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-18.webp', ancho: 1600, alto: 1600 },
    { ref: 'CP-E-19', src: '/images/colecciones/cirios-elaborados/cirios-elaborados-19.webp', ancho: 1600, alto: 1600 },
  ],
  'lazos-al-detalle': [
    { ref: 'BZ-D-01', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-01.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-D-02', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-02.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-D-03', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-03.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-04', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-04.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-05', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-05.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-D-06', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-06.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-07', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-07.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-D-08', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-08.webp', ancho: 1200, alto: 930 },
    { ref: 'BZ-D-09', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-09.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-10', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-10.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-11', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-11.webp', ancho: 1200, alto: 1500 },
    { ref: 'BZ-D-12', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-12.webp', ancho: 1200, alto: 1500 },
    { ref: 'BZ-D-13', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-13.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-D-14', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-14.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-D-15', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-15.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-D-16', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-16.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-17', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-17.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-18', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-18.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-19', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-19.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-20', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-20.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-21', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-21.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-22', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-22.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-D-23', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-23.webp', ancho: 1200, alto: 900 },
    { ref: 'BZ-D-24', src: '/images/colecciones/lazos-al-detalle/lazos-al-detalle-24.webp', ancho: 1600, alto: 1600 },
  ],
  'lazos-basicos': [
    { ref: 'BZ-B-01', src: '/images/colecciones/lazos-basicos/lazos-basicos-01.webp', ancho: 1600, alto: 1200 },
    { ref: 'BZ-B-02', src: '/images/colecciones/lazos-basicos/lazos-basicos-02.webp', ancho: 766, alto: 574 },
    { ref: 'BZ-B-03', src: '/images/colecciones/lazos-basicos/lazos-basicos-03.webp', ancho: 1440, alto: 1440 },
    { ref: 'BZ-B-04', src: '/images/colecciones/lazos-basicos/lazos-basicos-04.webp', ancho: 1600, alto: 1199 },
    { ref: 'BZ-B-05', src: '/images/colecciones/lazos-basicos/lazos-basicos-05.webp', ancho: 1600, alto: 1200 },
    { ref: 'BZ-B-06', src: '/images/colecciones/lazos-basicos/lazos-basicos-06.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-B-07', src: '/images/colecciones/lazos-basicos/lazos-basicos-07.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-B-08', src: '/images/colecciones/lazos-basicos/lazos-basicos-08.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-B-09', src: '/images/colecciones/lazos-basicos/lazos-basicos-09.webp', ancho: 1200, alto: 900 },
    { ref: 'BZ-B-10', src: '/images/colecciones/lazos-basicos/lazos-basicos-10.webp', ancho: 1200, alto: 900 },
    { ref: 'BZ-B-11', src: '/images/colecciones/lazos-basicos/lazos-basicos-11.webp', ancho: 765, alto: 571 },
    { ref: 'BZ-B-12', src: '/images/colecciones/lazos-basicos/lazos-basicos-12.webp', ancho: 300, alto: 300 },
    { ref: 'BZ-B-13', src: '/images/colecciones/lazos-basicos/lazos-basicos-13.webp', ancho: 768, alto: 1024 },
    { ref: 'BZ-B-14', src: '/images/colecciones/lazos-basicos/lazos-basicos-14.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-B-15', src: '/images/colecciones/lazos-basicos/lazos-basicos-15.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-B-16', src: '/images/colecciones/lazos-basicos/lazos-basicos-16.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-B-17', src: '/images/colecciones/lazos-basicos/lazos-basicos-17.webp', ancho: 1600, alto: 1600 },
  ],
  'lazos-elaborados': [
    { ref: 'BZ-E-01', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-01.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-E-02', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-02.webp', ancho: 1441, alto: 1600 },
    { ref: 'BZ-E-03', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-03.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-E-04', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-04.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-05', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-05.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-06', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-06.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-07', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-07.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-08', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-08.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-09', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-09.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-10', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-10.webp', ancho: 600, alto: 600 },
    { ref: 'BZ-E-11', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-11.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-12', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-12.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-13', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-13.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-E-14', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-14.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-15', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-15.webp', ancho: 1024, alto: 768 },
    { ref: 'BZ-E-16', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-16.webp', ancho: 1024, alto: 1024 },
    { ref: 'BZ-E-17', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-17.webp', ancho: 300, alto: 300 },
    { ref: 'BZ-E-18', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-18.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-19', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-19.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-20', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-20.webp', ancho: 1600, alto: 1200 },
    { ref: 'BZ-E-21', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-21.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-E-22', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-22.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-23', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-23.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-E-24', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-24.webp', ancho: 1051, alto: 1600 },
    { ref: 'BZ-E-25', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-25.webp', ancho: 1200, alto: 1200 },
    { ref: 'BZ-E-26', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-26.webp', ancho: 1051, alto: 1600 },
    { ref: 'BZ-E-27', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-27.webp', ancho: 1200, alto: 1059 },
    { ref: 'BZ-E-28', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-28.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-E-29', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-29.webp', ancho: 1600, alto: 1600 },
    { ref: 'BZ-E-30', src: '/images/colecciones/lazos-elaborados/lazos-elaborados-30.webp', ancho: 1200, alto: 1600 },
  ],
  'lazos-personalizados': [
    { ref: 'BZ-L-01', src: '/images/colecciones/lazos-personalizados/lazos-personalizados-01.webp', ancho: 1600, alto: 1200 },
    { ref: 'BZ-L-02', src: '/images/colecciones/lazos-personalizados/lazos-personalizados-02.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-L-03', src: '/images/colecciones/lazos-personalizados/lazos-personalizados-03.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-L-04', src: '/images/colecciones/lazos-personalizados/lazos-personalizados-04.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-L-05', src: '/images/colecciones/lazos-personalizados/lazos-personalizados-05.webp', ancho: 1200, alto: 1600 },
    { ref: 'BZ-L-06', src: '/images/colecciones/lazos-personalizados/lazos-personalizados-06.webp', ancho: 1200, alto: 1600 },
  ],
  'mesa-basicas': [
    { ref: 'MB-B-01', src: '/images/colecciones/mesa-basicas/mesa-basicas-01.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-B-02', src: '/images/colecciones/mesa-basicas/mesa-basicas-02.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-B-03', src: '/images/colecciones/mesa-basicas/mesa-basicas-03.webp', ancho: 1200, alto: 1200 },
    { ref: 'MB-B-04', src: '/images/colecciones/mesa-basicas/mesa-basicas-04.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-B-05', src: '/images/colecciones/mesa-basicas/mesa-basicas-05.webp', ancho: 768, alto: 1024 },
    { ref: 'MB-B-06', src: '/images/colecciones/mesa-basicas/mesa-basicas-06.webp', ancho: 768, alto: 1024 },
    { ref: 'MB-B-07', src: '/images/colecciones/mesa-basicas/mesa-basicas-07.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-B-08', src: '/images/colecciones/mesa-basicas/mesa-basicas-08.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-B-09', src: '/images/colecciones/mesa-basicas/mesa-basicas-09.webp', ancho: 1200, alto: 792 },
    { ref: 'MB-B-10', src: '/images/colecciones/mesa-basicas/mesa-basicas-10.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-B-11', src: '/images/colecciones/mesa-basicas/mesa-basicas-11.webp', ancho: 1200, alto: 1200 },
    { ref: 'MB-B-12', src: '/images/colecciones/mesa-basicas/mesa-basicas-12.webp', ancho: 1600, alto: 1200 },
    { ref: 'MB-B-13', src: '/images/colecciones/mesa-basicas/mesa-basicas-13.webp', ancho: 1200, alto: 1200 },
    { ref: 'MB-B-14', src: '/images/colecciones/mesa-basicas/mesa-basicas-14.webp', ancho: 1200, alto: 1499 },
    { ref: 'MB-B-15', src: '/images/colecciones/mesa-basicas/mesa-basicas-15.webp', ancho: 600, alto: 750 },
    { ref: 'MB-B-16', src: '/images/colecciones/mesa-basicas/mesa-basicas-16.webp', ancho: 600, alto: 750 },
    { ref: 'MB-B-17', src: '/images/colecciones/mesa-basicas/mesa-basicas-17.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-B-18', src: '/images/colecciones/mesa-basicas/mesa-basicas-18.webp', ancho: 1600, alto: 1200 },
    { ref: 'MB-B-19', src: '/images/colecciones/mesa-basicas/mesa-basicas-19.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-B-20', src: '/images/colecciones/mesa-basicas/mesa-basicas-20.webp', ancho: 768, alto: 1024 },
    { ref: 'MB-B-21', src: '/images/colecciones/mesa-basicas/mesa-basicas-21.webp', ancho: 1200, alto: 1600 },
    { ref: 'MB-B-22', src: '/images/colecciones/mesa-basicas/mesa-basicas-22.webp', ancho: 1200, alto: 1600 },
    { ref: 'MB-B-23', src: '/images/colecciones/mesa-basicas/mesa-basicas-23.webp', ancho: 1600, alto: 1200 },
    { ref: 'MB-B-24', src: '/images/colecciones/mesa-basicas/mesa-basicas-24.webp', ancho: 1600, alto: 1600 },
    { ref: 'MB-B-25', src: '/images/colecciones/mesa-basicas/mesa-basicas-25.webp', ancho: 1600, alto: 1200 },
  ],
  'mesa-elaboradas': [
    { ref: 'MB-E-01', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-01.webp', ancho: 1600, alto: 1200 },
    { ref: 'MB-E-02', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-02.webp', ancho: 1200, alto: 1200 },
    { ref: 'MB-E-03', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-03.webp', ancho: 1200, alto: 1200 },
    { ref: 'MB-E-04', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-04.webp', ancho: 1200, alto: 1499 },
    { ref: 'MB-E-05', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-05.webp', ancho: 1034, alto: 619 },
    { ref: 'MB-E-06', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-06.webp', ancho: 1200, alto: 1600 },
    { ref: 'MB-E-07', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-07.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-E-08', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-08.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-E-09', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-09.webp', ancho: 1200, alto: 900 },
    { ref: 'MB-E-10', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-10.webp', ancho: 1200, alto: 1200 },
    { ref: 'MB-E-11', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-11.webp', ancho: 1200, alto: 1199 },
    { ref: 'MB-E-12', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-12.webp', ancho: 1200, alto: 1199 },
    { ref: 'MB-E-13', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-13.webp', ancho: 1200, alto: 1200 },
    { ref: 'MB-E-14', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-14.webp', ancho: 1600, alto: 1200 },
    { ref: 'MB-E-15', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-15.webp', ancho: 1600, alto: 1200 },
    { ref: 'MB-E-16', src: '/images/colecciones/mesa-elaboradas/mesa-elaboradas-16.webp', ancho: 1600, alto: 1200 },
  ],
  'navidad': [
    { ref: 'NV-01', src: '/images/colecciones/navidad/navidad-01.jpeg', ancho: 826, alto: 1100 },
    { ref: 'NV-02', src: '/images/colecciones/navidad/navidad-02.jpeg', ancho: 826, alto: 1100 },
    { ref: 'NV-03', src: '/images/colecciones/navidad/navidad-03.jpeg', ancho: 826, alto: 1100 },
    { ref: 'NV-04', src: '/images/colecciones/navidad/navidad-04.jpeg', ancho: 826, alto: 1100 },
    { ref: 'NV-09', src: '/images/colecciones/navidad/navidad-09.jpeg', ancho: 826, alto: 1100 },
  ],
  'toallas-bautizo': [
    { ref: 'TB-01', src: '/images/colecciones/toallas-bautizo/toallas-bautizo-01.jpeg', ancho: 826, alto: 1100 },
    { ref: 'TB-02', src: '/images/colecciones/toallas-bautizo/toallas-bautizo-02.jpeg', ancho: 1100, alto: 852 },
    { ref: 'TB-03', src: '/images/colecciones/toallas-bautizo/toallas-bautizo-03.jpeg', ancho: 826, alto: 1100 },
    { ref: 'TB-04', src: '/images/colecciones/toallas-bautizo/toallas-bautizo-04.jpeg', ancho: 826, alto: 1100 },
    { ref: 'TB-05', src: '/images/colecciones/toallas-bautizo/toallas-bautizo-05.jpeg', ancho: 826, alto: 1100 },
  ],
  'toallas-bautizo-vela': [
    { ref: 'PK-01', src: '/images/colecciones/toallas-bautizo-vela/toallas-bautizo-vela-01.jpeg', ancho: 826, alto: 1100 },
    { ref: 'PK-02', src: '/images/colecciones/toallas-bautizo-vela/toallas-bautizo-vela-02.jpeg', ancho: 826, alto: 1100 },
    { ref: 'PK-03', src: '/images/colecciones/toallas-bautizo-vela/toallas-bautizo-vela-03.jpeg', ancho: 826, alto: 1100 },
    { ref: 'PK-04', src: '/images/colecciones/toallas-bautizo-vela/toallas-bautizo-vela-04.jpeg', ancho: 826, alto: 1100 },
    { ref: 'PK-05', src: '/images/colecciones/toallas-bautizo-vela/toallas-bautizo-vela-05.jpeg', ancho: 826, alto: 1100 },
  ],
};
